# Generated by Django 3.1.7 on 2021-05-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0003_auto_20210521_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='未知用户', max_length=64),
        ),
    ]
